config/routes.rb
Rails.application.routes.draw do
  get 'react_examples/component', to: 'react_examples#component', as: :component
  resources :fights, except: [:update, :update, :destroy]
  resources :fighters do
    collection do
      get 'most_wins'
      get 'most_fights'
    end
  end

  root 'fights#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :fighter
  validates :author, :body, presence: true
end

app/models/fight.rb
class Fight < ActiveRecord::Base
  has_many :fighter_fights
  has_many :fighters, through: :fighter_fights

  validate :has_two_fighters

  after_create :set_winner, :update_fighters

  def has_two_fighters
    if fighters.size != 2
      errors.add(:fight, "has to have 2 fighters")
    end
  end

  def set_winner
    update_attribute(:winner_id, calculate_winner)
  end

  def calculate_winner
    fighters.first.points_sum > fighters.last.points_sum ? fighters.first.id : fighters.last.id
  end

  def update_fighters
    fighters.first.id == winner_id ? lvl_up(fighters.first, fighters.last) : lvl_up(fighters.last, fighters.first)
  end

  def lvl_up winner, looser
    winner.lvl_up 2
    looser.lvl_up
  end
end

app/models/fighter.rb
class Fighter < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  has_many :fighter_skills, inverse_of: :fighter, autosave: true, dependent: :destroy
  has_many :fighter_fights
  has_many :fights, through: :fighter_fights
  has_many :skills, through: :fighter_skills
  has_many :comments

  accepts_nested_attributes_for :fighter_skills, allow_destroy: :true, reject_if: :all_blank

  validates :nickname, presence: true, uniqueness: true

  scope :most_experienced, -> { where('experience > 1').order(experience: :desc) }
  scope :most_fights, -> { joins(:fights).group('fighters.id').order("count(fighters.id) DESC, last_name ASC") }
  scope :most_wins, -> { joins('LEFT JOIN fights ON fighters.id = fights.winner_id').group('fighters.id').order("count(fights.winner_id) DESC, last_name ASC") }

  def points_sum
    experience + fighter_skills.count + fighter_skills.map(&:value).sum
  end

  def lvl_up(xp = 1)
    increment!(:experience, xp)
  end

  def fights_won
    fights.where(winner_id: id)
  end
end

app/models/fighter_fight.rb
class FighterFight < ActiveRecord::Base
  belongs_to :fighter
  belongs_to :fight

  validates :fighter, uniqueness: { scope: :fight, message: "duplicated fighter" }
end

app/models/fighter_skill.rb
class FighterSkill < ActiveRecord::Base

  belongs_to :fighter, inverse_of: :fighter_skills
  belongs_to :skill

  accepts_nested_attributes_for :skill

  validates_uniqueness_of :skill_id, scope: :fighter_id
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :fighter_skills
  has_many :fighters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @fighter = Fighter.find(params[:fighter_id])
    @comment = @fighter.comments.build(comment_params) # strong parameters
    if @comment.save
      respond_to do |format|
        format.html do
          flash[:success] = 'Comment posted.'
          redirect_to @post
        end
        format.js
      end
    else
      render @fighter
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @fighter = @comment.fighter
    @comment.destroy
    respond_to do |format|
      format.html do
        flash[:success] = 'Comment deleted.'
        redirect_to @fighter
      end
      format.js
    end
  end
end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  before_action :set_fighter, only: [:show, :edit, :update, :destroy]

  # GET /fighters
  # GET /fighters.json
  def index
    @fighters = Fighter.all.includes(:skills)
  end

  # GET /fighters/1
  # GET /fighters/1.json
  def show
    @comments = @fighter.comments
    @new_comment = @fighter.comments.new

    respond_to do |format|
      format.html
      format.json { render json: @fighter }
    end
  end

  def most_fights
    @fighters = Fighter.most_fights.includes(:skills)
    render 'index'
  end

  def most_wins
    @fighters = Fighter.most_wins.includes(:skills)
    render 'index'
  end
  # GET /fighters/new
  def new
    @fighter = Fighter.new
    @fighter.fighter_skills.build
    @skills = Skill.all
  end

  # GET /fighters/1/edit
  def edit
  end

  # POST /fighters
  # POST /fighters.json
  def create

    @fighter = Fighter.new(fighter_params)
    @skills = Skill.all

    respond_to do |format|
      if @fighter.save
        format.html { redirect_to @fighter, notice: 'Fighter was successfully created.' }
        format.json { render :show, status: :created, location: @fighter }
      else
        format.html { render :new }
        format.json { render json: @fighter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fighters/1
  # PATCH/PUT /fighters/1.json
  def update
    respond_to do |format|
      if @fighter.update(fighter_params)
        format.html { redirect_to @fighter, notice: 'Fighter was successfully updated.' }
        format.json { render :show, status: :ok, location: @fighter }
      else
        format.html { render :edit }
        format.json { render json: @fighter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fighters/1
  # DELETE /fighters/1.json
  def destroy
    @fighter.destroy
    respond_to do |format|
      format.html { redirect_to fighters_url, notice: 'Fighter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fighter
      @fighter = Fighter.includes(:skills).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fighter_params
      params.require(:fighter).permit(:first_name, :last_name, :nickname, :image, :remote_image_url, fighter_skills_attributes: [:skill_id, :value])
    end
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  before_action :set_fight, only: [:show, :edit, :update, :destroy]

  # GET /fights
  # GET /fights.json
  def index
    @fights = Fight.all.includes(:fighters)
  end

  # GET /fights/1
  # GET /fights/1.json
  def show
  end

  # GET /fights/new
  def new
    @fight = Fight.new
    @fighters = Fighter.all
  end

  # GET /fights/1/edit
  def edit
  end

  # POST /fights
  # POST /fights.json
  def create
    @fight = build_fight(Fight.new)
    respond_to do |format|
      if @fight.save
        format.html { redirect_to @fight, notice: 'Fight was successfully created.' }
        format.json { render :show, status: :created, location: @fight }
      else
        @fighters = Fighter.all
        format.html { render :new }
        format.json { render json: @fight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fights/1
  # PATCH/PUT /fights/1.json
  def update
    respond_to do |format|
      if @fight.update(fight_params)
        format.html { redirect_to @fight, notice: 'Fight was successfully updated.' }
        format.json { render :show, status: :ok, location: @fight }
      else
        format.html { render :edit }
        format.json { render json: @fight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fights/1
  # DELETE /fights/1.json
  def destroy
    @fight.destroy
    respond_to do |format|
      format.html { redirect_to fights_url, notice: 'Fight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fight
      @fight = Fight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fight_params
      params.require(:fight).permit(fighters: [:fighter_id, :opponent_id])
    end

    def build_fight(fight)
      fight.fighters << find_fighters
      return fight
    end

    def find_fighters
      Fighter.where(id: fight_params[:fighters].values)
    end
end

app/controllers/react_examples_controller.rb
class ReactExamplesController < ApplicationController
  def component
    @name = 'test'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fighters_helper.rb
module FightersHelper
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/views/fighters/_displayFighter.html.erb
nbmbnmbnmbnmnmnmnmnmb
vbnbnbv
nbvnbvn vbn

app/views/fighters/_errors.html.erb
<div id="error_explanation">
      <h2><%= pluralize(@fighter.errors.count, "error") %> prohibited this fighter from being saved:</h2>

      <ul>
      <% @fighter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

app/views/fighters/_form.html.erb
<%= form_for @fighter, html: { multipart: true } do |f| %>
  <% if @fighter.errors.any? %>
    <%= render 'errors' %>
  <% end %>

  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </div>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field" id="imageField">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "fromPc" %>
    <%= f.text_field :remote_image_url, class: "fromNet" %>
  </div>

  <%= f.fields_for :fighter_skills do |fs| %>
    <div class="container">
      <div class="row skillsGroup">
        <div class="skillSelect">
          <%= fs.collection_select :skill_id, @skills.order(:name), :id, :name, prompt: "Select skill"%>
          <%= fs.number_field :value, min: 0 %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= button_tag "Add Skill", type: "button", id: "addButton", class: "btn btn-primary" %>
    <%= button_tag "Remove", type: "button", id: "removeButton", class: "btn btn-danger" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary", id: "submitButton" %>
  </div>
<% end %>

app/views/fighters/edit.html.erb
<h1>Editing Fighter</h1>

<%= render 'form' %>

<%= link_to 'Show', @fighter %> |
<%= link_to 'Back', fighters_path %>

app/views/fighters/index.html.erb
<h1 class="text-center">Listing Fighters</h1>

<% @fighters.each do |fighter| %>


    <div class="row wrapper">
      <div class="col-sm-4 portfolio-item">
        <%= image_tag(fighter.image.normal.url, class: "img-responsive circle-image") unless fighter.image.nil? %>
      </div>

      <div class="col-sm-4">
        <div class="row">
          <h3>
            <%= link_to fighter.nickname, fighter_path(fighter) %>
          </h3>
          <p>
            <%= "#{fighter.first_name} #{fighter.last_name}" %> | <%= "#{fighter.fights_won.count} fights won" %>
          </p>
        </div>
        <div class="row">
          <ul>
            <% fighter.fighter_skills.each do |fskill| %>
              <li><%= fskill.skill.name+" "+fskill.value.to_s %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
<% end %>

<%= link_to 'New Fight', new_fight_path %>

app/views/fighters/new.html.erb
<div class="container">
  <div class="row wrapper">
    <div class="col-sm-4">

      <h1>New Fighter</h1>

      <%= render 'form' %>

      <%= link_to 'Back', fighters_path, class: "btn" %>

    </div>
  </div>
</div>

app/views/fighters/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row wrapper">
  <div class="col-sm-2 portfolio-item">
    <%= image_tag(@fighter.image.normal.url, class: "img-responsive circle-image") unless @fighter.image.nil? %>
  </div>

  <div class="col-sm-2">
    <div class="row">
      <h3>
        <%= link_to @fighter.nickname, fighter_path(@fighter) %>
      </h3>
      <p><%= "#{@fighter.first_name} #{@fighter.last_name}" %></p>
    </div>
    <div class="row">
      <ul>
        <% @fighter.fighter_skills.each do |fskill| %>
          <li><%= fskill.skill.name+" "+fskill.value.to_s %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_fighter_path(@fighter) %> |
<%= link_to 'Back', fighters_path %>

app/views/fights/_displayFighter.html.erb
sdfdsfsdfsdfsdfsff

app/views/fights/_errors.html.erb
<div id="error_explanation">
  <h2><%= pluralize(@fight.errors.count, "error") %> prohibited this fight from being saved:</h2>

  <ul>
  <% @fight.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>

app/views/fights/_form.html.erb
<%= form_for @fight do |f| %>
  <% if @fight.errors.any? %>
    <%= render 'errors' %>
  <% end %>
  <%= f.fields_for :fighters do |fighter| %>

    <div class="row wrapper">
      <div class="col-sm-4 portfolio-item">
        <%= fighter.collection_select :fighter_id, @fighters.order(:nickname), :id, :nickname, prompt: "Select fighter" %>
        <span id="fighter-area">
        </span>
      </div>

      <div class="col-sm-2">
        <h2 class="text-center">VS</h2>
      </div>

      <div class="col-sm-4 portfolio-item">
        <%= fighter.collection_select :opponent_id, @fighters.order(:nickname), :id, :nickname, prompt: "Select fighter" %>
        <span id="opponent-area">
        </span>
      </div>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit class: "btn btn-primary", id: "sendButton" %>
  </div>
<% end %>

app/views/fights/edit.html.erb
<h1>Editing Fight</h1>

<%= render 'form' %>

<%= link_to 'Show', @fight %> |
<%= link_to 'Back', fights_path %>

app/views/fights/index.html.erb
  <h1 class="text-center">Listing Fights</h1>

  <% @fights.each.with_index(1) do |fight, i| %>



    <div class="row">
      <div class="col-lg-12">
          <h1 class="page-header text-center">#<%= i %></h1>
      </div>
    </div>

    <div class="row wrapper">
      <div class="col-sm-2 portfolio-item">
        <%= image_tag(fight.fighters.first.image.normal.url, class: "img-responsive circle-image") unless fight.fighters.first.image.nil? %>
        <h3>
            <%= link_to fight.fighters.first.nickname, fighter_path(fight.fighters.first) %>
        </h3>
        <p><%= "#{fight.fighters.first.first_name} #{fight.fighters.first.last_name}" %></p>
      </div>

      <div class="col-sm-2">
        <h2 class="text-center">VS</h2>
      </div>

      <div class="col-sm-2 portfolio-item">
            <%= image_tag(fight.fighters.last.image.normal.url, class: "img-responsive circle-image") unless fight.fighters.last.image.nil? %>
        <h3>
          <%= link_to fight.fighters.last.nickname, fighter_path(fight.fighters.last) %>
        </h3>
        <p><%= "#{fight.fighters.last.first_name} #{fight.fighters.last.last_name}" %></p>
      </div>
    </div>

<% end %>

<%= link_to 'New Fight', new_fight_path %>

app/views/fights/new.html.erb
<div class="row wrapper">
  <h1 class="text-center">New Fight</h1>
</div>

<div class="row wrapper">
  <%= render 'form' %>
</div>

<%= link_to 'Back', fights_path %>

app/views/fights/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_fight_path(@fight) %> |
<%= link_to 'Back', fights_path %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-lg-12">
      <p>Copyright &copy; Your Website 2016</p>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Fight Club</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Fights <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'New Fight', new_fight_path %></li>
            <li><%= link_to 'All', fights_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Fighters <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'New Fighter', new_fighter_path %></li>
            <li><%= link_to 'All', fighters_path %></li>
            <li><%= link_to 'Most experienced', most_fights_fighters_path %></li>
            <li><%= link_to 'Most Wins', most_wins_fighters_path %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_react_hot_assets.html.erb
<% if Rails.env.development? %>
  <script src='http://localhost:8080/assets/react_bundle.js'></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FightClub2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="col">
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/react_examples/component.html.erb
<%= react_component('HelloWorld', { name: @name }, { server_side: true }) %>